sena_management: {
  institutional_structure: {
    style.fill: "#FADBD8"
    style.stroke: "#CB4335"

    macroregion: {
      shape: sql_table

      macroregion_id: uuid {constraint: primary_key}
      region_name: varchar
      status: varchar
    }

    microregion: {
      shape: sql_table

      microregion_id: uuid {constraint: primary_key}
      macroregion_id: uuid {constraint: foreign_key}
      microregion_name: varchar
      status: varchar
    }

    training_center: {
      shape: sql_table

      training_center_id: uuid {constraint: primary_key}
      microregion_id: uuid {constraint: foreign_key}
      code: varchar
      center_name: varchar
      center_type: varchar
      status: varchar
    }

    institutional_unit: {
      shape: sql_table

      unit_id: uuid {constraint: primary_key}
      training_center_id: uuid {constraint: foreign_key}
      municipality_name: varchar
      unit_name: varchar
      unit_type: varchar
      phone: varchar
      status: varchar
    }

    instructor_assignment: {
      shape: sql_table

      assignment_id: uuid {constraint: primary_key}
      unit_id: uuid {constraint: foreign_key}
      start_date: date
      end_date: date
      status: varchar
    }

    location: {
      shape: sql_table

      location_id: uuid {constraint: primary_key}
      unit_id: uuid {constraint: foreign_key}
      address
      postal_code: varchar
      latitude: decimal
      longitude: decimal
      status: varchar
    }
  }

  institutional_structure.macroregion.macroregion_id -> institutional_structure.microregion.macroregion_id

  institutional_structure.microregion.microregion_id -> institutional_structure.training_center.microregion_id

  institutional_structure.training_center.training_center_id -> institutional_structure.institutional_unit.training_center_id

  institutional_structure.institutional_unit.unit_id -> institutional_structure.instructor_assignment.unit_id

  institutional_structure.institutional_unit.unit_id -> institutional_structure.location.unit_id
}
